Repository contane/charts, pull requests merged in 2024-07, with the labels that each got.

#6 chore: Configure Renovate to update appVersion
  charts/foreman/Chart.yaml
  renovate.json
Labels: type::chore

#7 chore(foreman): Update Chart version to 0.1.0
  charts/foreman/Chart.yaml
Labels: type::chore

#2 chore: Configure chart-releaser action
  .github/configs/cr.yml
  .github/workflows/release.yml
Labels: type::chore

#8 chore: Use contane-bot for automatic actions
  .github/configs/cr.yml
  .github/workflows/release.yml
Labels: type::chore

#11 chore(foreman): Add optional metadata into Chart.yaml
  charts/foreman/Chart.yaml
Labels: type::chore

#13 fix(foreman): Bump chart version
  charts/foreman/Chart.yaml
Labels: type::fix

#15 chore: Add pull request and issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
Labels: type::chore

#14 docs: Add README.md
  README.md
  charts/foreman/README.md
Labels: type::docs

#16 docs(foreman): Improve documentation of nameOverride parameter
  charts/foreman/Chart.yaml
  charts/foreman/values.yaml
Labels: type::docs

#19 chore: Configure Renovate to bump chart versions
  renovate.json
Labels: type::chore

#18 chore: Add a CI job to verify chart versions are bumped
  .github/workflows/chart-version-bump.yml
Labels: type::chore

#20 chore: Create .github/CODEOWNERS
  .github/CODEOWNERS
Labels: type::chore

#23 chore: Use chart name as Renovate scope
  renovate.json
Labels: type::chore

#17 chore: Configure Chart signing
  .github/configs/cr.yml
  .github/workflows/release.yml
  README.md
Labels: type::chore

#28 chore(foreman): Add public key information into Chart.yaml
  charts/foreman/Chart.yaml
Labels: type::chore

#30 chore: Add missing public key
  .github/workflows/release.yml
Labels: type::chore

#31 chore: Lint pull request title
  .github/workflows/pr-title.yml
Labels: type::chore

#35 chore(repo): Add README.md auto-update workflow
  .github/workflows/update-mds.yml
Labels: type::chore

#36 docs(foreman): Fix values.yaml documentation format
  charts/foreman/Chart.yaml
  charts/foreman/README.md
  charts/foreman/values.yaml
Labels: type::docs

#38 chore(repo): Use public key in binary format
  .github/workflows/release.yml
Labels: type::chore

#39 chore: Update PR template
  .github/pull_request_template.md
Labels: type::chore

#42 chore(repo): Change Renovate commit scope to repo
  renovate.json
Labels: type::chore

#43 chore(repo): Fix .github path in Renovate config
  renovate.json
Labels: type::chore
